# Generated by Django 4.1.3 on 2022-12-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0009_daysoftheweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysOfTheWeek',
        ),
    ]
