# Generated by Django 4.1.3 on 2022-12-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0033_daysoftheweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PassWorkouts',
        ),
    ]
