# Generated by Django 4.1.3 on 2022-12-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0034_exercise_sets_delete_passworkouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
